import { labelFor } from "@/lib/labels";

const styles: Record<string, string> = {
  READY: "border-ready text-ready bg-emerald-50",
  FULL_READY: "border-ready text-ready bg-emerald-50",
  WARMUP: "border-warmup text-warmup bg-amber-50",
  FULL_WARMUP: "border-warmup text-warmup bg-amber-50",
  STALE: "border-stale text-stale bg-red-50",
  FULL_STALE: "border-stale text-stale bg-red-50",
  MISSING: "border-missing text-missing bg-gray-50",
  MISSING_SPOT: "border-missing text-missing bg-gray-50",
  FULL_MISSING_SPOT: "border-missing text-missing bg-gray-50",
  MISSING_FUTURES: "border-stale text-stale bg-red-50",
  FULL_MISSING_FUTURES: "border-stale text-stale bg-red-50",
  MISSING_OI: "border-warmup text-warmup bg-amber-50",
  FULL_MISSING_OI: "border-warmup text-warmup bg-amber-50",
  MISSING_FUNDING: "border-warmup text-warmup bg-amber-50",
  FULL_MISSING_FUNDING: "border-warmup text-warmup bg-amber-50",
  FULL_ACTIVE: "border-blue-700 text-blue-700 bg-blue-50",
  ACTIVE: "border-ready text-ready bg-emerald-50",
  LIGHT_WATCH: "border-slate-500 text-slate-700 bg-slate-50",
  NOT_ACTIVE: "border-missing text-missing bg-gray-50",
  RICH_READY: "border-ready text-ready bg-emerald-50",
  RICH_WARMUP: "border-warmup text-warmup bg-amber-50",
  RICH_STALE: "border-stale text-stale bg-red-50",
  RICH_MISSING: "border-missing text-missing bg-gray-50",
  AGG_READY: "border-ready text-ready bg-emerald-50",
  AGG_INCOMPLETE: "border-warmup text-warmup bg-amber-50",
  AGG_WARMUP: "border-missing text-missing bg-gray-50",
  AGG_STALE: "border-stale text-stale bg-red-50",
  AGG_MISSING_SPOT: "border-missing text-missing bg-gray-50",
  ALIGNED: "border-ready text-ready bg-emerald-50",
  INCOMPLETE: "border-warmup text-warmup bg-amber-50",
  NO_DATA: "border-missing text-missing bg-gray-50",
  FRESH: "border-ready text-ready bg-emerald-50",
  FUNDING_ALIGNED: "border-ready text-ready bg-emerald-50",
  FUNDING_CARRIED_FORWARD: "border-warmup text-warmup bg-amber-50",
  FUNDING_STALE: "border-stale text-stale bg-red-50",
  FUNDING_MISSING: "border-missing text-missing bg-gray-50",
  FEATURE_READY: "border-ready text-ready bg-emerald-50",
  FEATURE_PARTIAL: "border-warmup text-warmup bg-amber-50",
  FEATURE_BLOCKED: "border-stale text-stale bg-red-50",
  CONTEXT_READY: "border-ready text-ready bg-emerald-50",
  CONTEXT_PARTIAL: "border-warmup text-warmup bg-amber-50",
  CONTEXT_BLOCKED: "border-stale text-stale bg-red-50",
  WATCHLIST_CONTEXT: "border-blue-700 text-blue-700 bg-blue-50",
  RADAR_ONLY: "border-warmup text-warmup bg-amber-50",
  READ_ONLY: "border-blue-700 text-blue-700 bg-blue-50",
  RISK_CONTEXT: "border-stale text-stale bg-red-50",
  BASELINE_CONTEXT: "border-line text-slate-700 bg-slate-50",
  BLOCKED: "border-stale text-stale bg-red-50",
  CLASSIFIER_READY: "border-ready text-ready bg-emerald-50",
  CLASSIFIER_PARTIAL: "border-warmup text-warmup bg-amber-50",
  CLASSIFIER_BLOCKED: "border-stale text-stale bg-red-50",
  OUTCOME_READY: "border-ready text-ready bg-emerald-50",
  OUTCOME_WAITING_DATA: "border-warmup text-warmup bg-amber-50",
  OUTCOME_INCOMPLETE: "border-warmup text-warmup bg-amber-50",
  OUTCOME_BLOCKED: "border-stale text-stale bg-red-50",
  PROMISING_FOR_FORWARD_TEST: "border-ready text-ready bg-emerald-50",
  PROMISING_FILTER: "border-ready text-ready bg-emerald-50",
  V3_FORWARD_HEALTHY_SHADOW: "border-ready text-ready bg-emerald-50",
  V3_FORWARD_MONITOR_MORE: "border-blue-700 text-blue-700 bg-blue-50",
  V3_FORWARD_WAITING_SAMPLE: "border-warmup text-warmup bg-amber-50",
  V3_FORWARD_WEAK: "border-stale text-stale bg-red-50",
  V3_FORWARD_INCONCLUSIVE: "border-line text-slate-700 bg-slate-50",
  V3_SHADOW_IMPROVES_V2: "border-ready text-ready bg-emerald-50",
  V3_SHADOW_MONITOR_MORE: "border-blue-700 text-blue-700 bg-blue-50",
  V3_SHADOW_WEAKER_THAN_V2: "border-stale text-stale bg-red-50",
  V3_SHADOW_INCONCLUSIVE: "border-line text-slate-700 bg-slate-50",
  V3_SAMPLE_TOO_SMALL: "border-warmup text-warmup bg-amber-50",
  REDUCES_DAMAGE: "border-blue-700 text-blue-700 bg-blue-50",
  NOISY_FILTER: "border-warmup text-warmup bg-amber-50",
  WORSE_THAN_BASELINE: "border-stale text-stale bg-red-50",
  REGIME_HELPFUL: "border-ready text-ready bg-emerald-50",
  REGIME_IMPROVES: "border-blue-700 text-blue-700 bg-blue-50",
  REGIME_NOISY: "border-warmup text-warmup bg-amber-50",
  REGIME_BAD: "border-stale text-stale bg-red-50",
  REGIME_UNKNOWN: "border-missing text-missing bg-gray-50",
  MONITOR_MORE: "border-blue-700 text-blue-700 bg-blue-50",
  NOISY: "border-warmup text-warmup bg-amber-50",
  REJECT: "border-stale text-stale bg-red-50",
  INSUFFICIENT_SAMPLE: "border-missing text-missing bg-gray-50",
  LABEL_READY: "border-ready text-ready bg-emerald-50",
  LABEL_PARTIAL: "border-warmup text-warmup bg-amber-50",
  LABEL_BLOCKED: "border-stale text-stale bg-red-50",
  SIGNAL_CANDIDATE: "border-blue-700 text-blue-700 bg-blue-50",
  CONFLICTED: "border-warmup text-warmup bg-amber-50",
  BLOCKED_DATA: "border-stale text-stale bg-red-50",
  PARTIAL_DATA: "border-warmup text-warmup bg-amber-50",
  MISSING_CANDLES: "border-stale text-stale bg-red-50",
  MISSING_ATR: "border-warmup text-warmup bg-amber-50",
  STALE_DATA: "border-stale text-stale bg-red-50",
  TIMEFRAME_READY: "border-ready text-ready bg-emerald-50",
  TIMEFRAME_PARTIAL_USABLE: "border-warmup text-warmup bg-amber-50",
  TIMEFRAME_NOT_READY: "border-stale text-stale bg-red-50",
  PHASE7_READY: "border-ready text-ready bg-emerald-50",
  WATCHLIST_FOR_MORE_DATA: "border-blue-700 text-blue-700 bg-blue-50",
  REJECT_FOR_PHASE7: "border-stale text-stale bg-red-50",
  HAS_CANDIDATES: "border-ready text-ready bg-emerald-50",
  NO_PHASE7_CANDIDATE_YET: "border-warmup text-warmup bg-amber-50",
  WAITING_FOR_APPROVED_CANDIDATE: "border-warmup text-warmup bg-amber-50",
  WAITING_FOR_CANDIDATE: "border-warmup text-warmup bg-amber-50",
  ACTIVE_FORWARD_TEST: "border-blue-700 text-blue-700 bg-blue-50",
  ACTIVE_LAB_SHADOW: "border-blue-700 text-blue-700 bg-blue-50",
  ACTIVE_APPROVED_SHADOW: "border-ready text-ready bg-emerald-50",
  FORWARD_TEST_COMPLETE: "border-ready text-ready bg-emerald-50",
  INPUT_ARTIFACT_MISSING: "border-stale text-stale bg-red-50",
  PHASE7_INFRA_READY_WAITING: "border-warmup text-warmup bg-amber-50",
  PHASE7_ACTIVE_FORWARD_TEST: "border-blue-700 text-blue-700 bg-blue-50",
  PHASE7_BLOCKED_BY_ERROR: "border-stale text-stale bg-red-50",
  PHASE7_DUAL_LANE_ACTIVE_LAB_SHADOW: "border-blue-700 text-blue-700 bg-blue-50",
  PHASE7_DUAL_LANE_ACTIVE_APPROVED_SHADOW: "border-ready text-ready bg-emerald-50",
  PHASE7_DUAL_LANE_READY_WAITING: "border-warmup text-warmup bg-amber-50",
  PHASE7_DUAL_LANE_ERROR: "border-stale text-stale bg-red-50",
  APPROVED_SHADOW: "border-ready text-ready bg-emerald-50",
  LAB_SHADOW: "border-blue-700 text-blue-700 bg-blue-50",
  STRICT_APPROVED: "border-ready text-ready bg-emerald-50",
  LAB_NEAR_MISS: "border-blue-700 text-blue-700 bg-blue-50",
  WAITING_OUTCOME: "border-blue-700 text-blue-700 bg-blue-50",
  TP_FIRST: "border-ready text-ready bg-emerald-50",
  SL_FIRST: "border-stale text-stale bg-red-50",
  NEITHER: "border-line text-slate-700 bg-slate-50",
  NEITHER_CLOSE_AT_HORIZON: "border-line text-slate-700 bg-slate-50",
  TP_HIT: "border-ready text-ready bg-emerald-50",
  SL_HIT: "border-stale text-stale bg-red-50",
  BOTH_HIT_SAME_CANDLE: "border-warmup text-warmup bg-amber-50",
  EXPIRED: "border-line text-slate-700 bg-slate-50",
  UNKNOWN_FORWARD_DATA: "border-warmup text-warmup bg-amber-50",
  OPEN: "border-blue-700 text-blue-700 bg-blue-50",
  WAITING_DATA: "border-warmup text-warmup bg-amber-50",
  STALE_FORWARD_DATA: "border-stale text-stale bg-red-50",
  STALE_FOUND: "border-stale text-stale bg-red-50",
  CANNOT_EVALUATE: "border-stale text-stale bg-red-50",
  CANNOT_CREATE_EVENT_MISSING_REFERENCE: "border-stale text-stale bg-red-50",
  MISSING_ARTIFACT: "border-stale text-stale bg-red-50",
  SUCCESS: "border-ready text-ready bg-emerald-50",
  PARTIAL: "border-warmup text-warmup bg-amber-50",
  ERROR: "border-stale text-stale bg-red-50",
  RUNNING: "border-blue-700 text-blue-700 bg-blue-50",
  PASS: "border-ready text-ready bg-emerald-50",
  FAIL: "border-stale text-stale bg-red-50",
  INFO: "border-blue-700 text-blue-700 bg-blue-50",
  UNAVAILABLE: "border-missing text-missing bg-gray-50"
};

export function StatusBadge({ value }: { value?: string | null }) {
  const label = value || "-";
  return (
    <span
      className={`inline-flex max-w-72 justify-center whitespace-normal break-words rounded border px-2 py-1 text-center text-xs font-semibold ${styles[label] || "border-line text-ink bg-white"}`}
      title={label}
    >
      {labelFor(label)}
    </span>
  );
}
