const labels: Record<string, string> = {
  MID_SHORT_FUTURES_LED: "Mid Short + Futures Dominan",
  MID_SHORT_NON_FUTURES_LED: "Mid Short non-Futures Dominan",
  MID_SHORT: "Mid Short",
  MID_LONG: "Mid Long",
  EARLY_LONG: "Early Long",
  EARLY_SHORT: "Early Short",
  NO_SIGNAL_CONTEXT: "Belum ada setup",
  NO_SETUP: "Belum ada setup",
  BASELINE_CONTEXT: "Baseline / pembanding",
  RISK_CONTEXT: "Konteks risiko",
  RADAR_ONLY: "Pantauan saja",
  READ_ONLY: "Read-only",
  SIGNAL_CANDIDATE: "Calon sinyal",
  WATCHLIST_CONTEXT: "Candidate",
  WATCHLIST_FOR_MORE_DATA: "Pantau dulu",
  PHASE7_READY: "Siap forward-test",
  REJECT_FOR_PHASE7: "Ditolak oleh gate",
  WAITING_FOR_APPROVED_CANDIDATE: "Menunggu kandidat approved",
  WAITING_FOR_CANDIDATE: "Menunggu kandidat",
  ACTIVE_FORWARD_TEST: "Forward-test aktif",
  ACTIVE_LAB_SHADOW: "Lab shadow aktif",
  ACTIVE_APPROVED_SHADOW: "Approved shadow aktif",
  FORWARD_TEST_COMPLETE: "Forward-test selesai",
  INPUT_ARTIFACT_MISSING: "Artifact belum lengkap",
  PHASE7_INFRA_READY_WAITING: "Infra siap, menunggu",
  PHASE7_ACTIVE_FORWARD_TEST: "Shadow test aktif",
  PHASE7_BLOCKED_BY_ERROR: "Gate blocked",
  PHASE7_DUAL_LANE_ACTIVE_LAB_SHADOW: "Lab shadow aktif",
  PHASE7_DUAL_LANE_ACTIVE_APPROVED_SHADOW: "Approved shadow aktif",
  PHASE7_DUAL_LANE_READY_WAITING: "Menunggu kandidat",
  PHASE7_DUAL_LANE_ERROR: "Forward-test error",
  APPROVED_SHADOW: "Approved Shadow",
  LAB_SHADOW: "Lab Shadow",
  STRICT_APPROVED: "Strict approved",
  LAB_NEAR_MISS: "Lab near-miss",
  WAITING_OUTCOME: "Menunggu outcome",
  TP_FIRST: "TP duluan",
  SL_FIRST: "SL duluan",
  NEITHER: "Belum kena TP/SL",
  NEITHER_CLOSE_AT_HORIZON: "Close di horizon",
  TP_HIT: "Target referensi tersentuh",
  SL_HIT: "Stop referensi tersentuh",
  BOTH_HIT_SAME_CANDLE: "Target dan stop satu candle",
  EXPIRED: "Expired",
  UNKNOWN_FORWARD_DATA: "Data forward belum cukup",
  CANNOT_EVALUATE: "Tidak bisa dievaluasi",
  CANNOT_CREATE_EVENT_MISSING_REFERENCE: "Referensi belum lengkap",
  NOISY: "Masih noise",
  MONITOR_MORE: "Pantau lagi",
  PROMISING_FOR_FORWARD_TEST: "Menarik, belum final",
  PROMISING_FILTER: "Filter menarik",
  REDUCES_DAMAGE: "Mengurangi rugi",
  NOISY_FILTER: "Filter masih noise",
  WORSE_THAN_BASELINE: "Lebih buruk dari baseline",
  REGIME_HELPFUL: "Regime membantu",
  REGIME_IMPROVES: "Regime membaik",
  REGIME_NOISY: "Regime noise",
  REGIME_BAD: "Regime buruk",
  REGIME_UNKNOWN: "Regime belum jelas",
  RISK_ON: "Risk on",
  RISK_OFF: "Risk off",
  BTC_UP_BREADTH_WEAK: "BTC naik, market lemah",
  BTC_DOWN_BREADTH_STRONG: "BTC turun, market kuat",
  CHOPPY_OR_MIXED: "Choppy / mixed",
  BULLISH: "Bullish",
  BEARISH: "Bearish",
  FLAT: "Flat",
  UNKNOWN: "Unknown",
  BREADTH_STRONG: "Market breadth kuat",
  BREADTH_WEAK: "Market breadth lemah",
  BREADTH_MIXED: "Market breadth mixed",
  BREADTH_UNKNOWN: "Breadth belum jelas",
  VOL_HIGH: "Volatilitas tinggi",
  VOL_NORMAL: "Volatilitas normal",
  VOL_LOW: "Volatilitas rendah",
  VOL_UNKNOWN: "Volatilitas belum jelas",
  PROMISING: "Menarik, belum final",
  QUALITY_POSITIVE: "Kualitas positif",
  TOTAL_R_POSITIVE_MEDIAN_WEAK: "Total positif, median lemah",
  QUALITY_WEAK: "Kualitas lemah",
  NOISY_MIXED: "Campuran/noise",
  SAMPLE_TOO_SMALL: "Sample kecil",
  INSUFFICIENT_SAMPLE: "Sample kurang",
  REJECT: "Ditolak",
  PARTIAL_DATA: "Data sebagian",
  MISSING_ATR: "ATR belum tersedia",
  MISSING_CANDLES: "Candle belum cukup",
  TIMEFRAME_NOT_READY: "Timeframe belum siap",
  TIMEFRAME_PARTIAL_USABLE: "Bisa dipakai sebagian",
  TIMEFRAME_READY: "Timeframe siap",
  BLOCKED_DATA: "Data belum cukup",
  CONFLICTED: "Konteks campuran",
  BULLISH_CONTEXT: "Condong naik",
  BEARISH_CONTEXT: "Condong turun",
  MIXED_CONTEXT: "Campuran",
  MIXED: "Campuran",
  HIGH: "Tinggi",
  MEDIUM: "Sedang",
  LOW: "Rendah",
  HAS_CANDIDATES: "Ada kandidat lolos gate",
  NO_PHASE7_CANDIDATE_YET: "Belum ada kandidat lolos gate",
  READY: "Siap",
  WARMUP: "Pemanasan data",
  STALE: "Data tertinggal",
  MISSING_SPOT: "Spot belum tersedia",
  MISSING_FUTURES: "Futures belum tersedia",
  MISSING_OI: "OI belum tersedia",
  MISSING_FUNDING: "Funding belum tersedia",
  AGG_READY: "Siap",
  AGG_INCOMPLETE: "Belum lengkap",
  AGG_WARMUP: "Pemanasan data",
  AGG_STALE: "Data tertinggal",
  AGG_MISSING_SPOT: "Spot belum tersedia",
  ALIGNED: "Aligned",
  INCOMPLETE: "Belum lengkap",
  NO_DATA: "Belum ada data",
  FRESH: "Fresh",
  FUNDING_ALIGNED: "Funding aligned",
  FUNDING_CARRIED_FORWARD: "Funding carry-forward",
  FUNDING_STALE: "Funding stale",
  FUNDING_MISSING: "Funding missing",
  FEATURE_READY: "Feature siap",
  FEATURE_PARTIAL: "Feature sebagian",
  FEATURE_BLOCKED: "Feature blocked",
  CONTEXT_READY: "Context siap",
  CONTEXT_PARTIAL: "Context sebagian",
  CONTEXT_BLOCKED: "Context blocked",
  OUTCOME_READY: "Outcome siap",
  OUTCOME_WAITING_DATA: "Menunggu data",
  OUTCOME_INCOMPLETE: "Outcome belum lengkap",
  OUTCOME_BLOCKED: "Outcome blocked",
  ACTIVE: "Aktif",
  NOT_ACTIVE: "Tidak aktif",
  FULL_ACTIVE: "Full active",
  LIGHT_WATCH: "Light watch",
  PASS: "Pass",
  FAIL: "Fail",
  INFO: "Info",
  UNAVAILABLE: "Belum tersedia"
};

export function labelFor(value?: string | null): string {
  if (!value) return "-";
  return labels[value] || value.replaceAll("_", " ").toLowerCase().replace(/^\w/, (char) => char.toUpperCase());
}

export function compactReason(value?: string | null, max = 110): string {
  if (!value) return "-";
  return value.length > max ? `${value.slice(0, max - 1)}...` : value;
}
