const labels: Record<string, string> = {
  MID_SHORT_FUTURES_LED: "Mid Short + Futures Dominan",
  MID_SHORT_NON_FUTURES_LED: "Mid Short non-Futures Dominan",
  MID_SHORT: "Mid Short",
  MID_LONG: "Mid Long",
  EARLY_LONG: "Early Long",
  EARLY_SHORT: "Early Short",
  NO_SIGNAL_CONTEXT: "Belum ada setup",
  NO_SETUP: "Belum ada setup",
  BASELINE_CONTEXT: "Baseline / pembanding",
  RISK_CONTEXT: "Konteks risiko",
  RADAR_ONLY: "Radar saja",
  SIGNAL_CANDIDATE: "Kandidat signal",
  WATCHLIST_CONTEXT: "Watchlist",
  WATCHLIST_FOR_MORE_DATA: "Pantau dulu",
  PHASE7_READY: "Siap shadow forward-test",
  REJECT_FOR_PHASE7: "Ditolak untuk Phase 7",
  NOISY: "Terlalu noise",
  MONITOR_MORE: "Pantau lagi",
  PROMISING_FOR_FORWARD_TEST: "Layak diuji lanjut",
  PARTIAL_DATA: "Data sebagian",
  MISSING_ATR: "ATR belum tersedia",
  MISSING_CANDLES: "Candle belum cukup",
  TIMEFRAME_NOT_READY: "Timeframe belum siap",
  TIMEFRAME_PARTIAL_USABLE: "Bisa dipakai sebagian",
  TIMEFRAME_READY: "Timeframe siap",
  BLOCKED_DATA: "Data terblokir",
  CONFLICTED: "Konflik timeframe",
  BULLISH_CONTEXT: "Bullish context",
  BEARISH_CONTEXT: "Bearish context",
  MIXED_CONTEXT: "Campuran",
  HIGH: "Tinggi",
  MEDIUM: "Sedang",
  LOW: "Rendah",
  HAS_CANDIDATES: "Ada kandidat shadow",
  NO_PHASE7_CANDIDATE_YET: "Belum ada kandidat",
  READY: "Siap",
  WARMUP: "Pemanasan data",
  STALE: "Data stale",
  MISSING_SPOT: "Spot belum ada",
  MISSING_FUTURES: "Futures belum ada",
  MISSING_OI: "OI belum ada",
  MISSING_FUNDING: "Funding belum ada",
  AGG_READY: "Agregasi siap",
  AGG_INCOMPLETE: "Agregasi belum lengkap",
  ALIGNED: "Aligned",
  INCOMPLETE: "Belum lengkap",
  NO_DATA: "Belum ada data",
  FRESH: "Fresh",
  FUNDING_ALIGNED: "Funding aligned",
  FUNDING_CARRIED_FORWARD: "Funding carry-forward",
  FUNDING_STALE: "Funding stale",
  FUNDING_MISSING: "Funding missing",
  FEATURE_READY: "Feature siap",
  FEATURE_PARTIAL: "Feature sebagian",
  FEATURE_BLOCKED: "Feature blocked",
  CONTEXT_READY: "Context siap",
  CONTEXT_PARTIAL: "Context sebagian",
  CONTEXT_BLOCKED: "Context blocked",
  OUTCOME_READY: "Outcome siap",
  OUTCOME_WAITING_DATA: "Menunggu data",
  OUTCOME_INCOMPLETE: "Outcome belum lengkap",
  OUTCOME_BLOCKED: "Outcome blocked",
  ACTIVE: "Aktif",
  NOT_ACTIVE: "Tidak aktif",
  FULL_ACTIVE: "Full active",
  LIGHT_WATCH: "Light watch"
};

export function labelFor(value?: string | null): string {
  if (!value) return "-";
  return labels[value] || value.replaceAll("_", " ").toLowerCase().replace(/^\w/, (char) => char.toUpperCase());
}

export function compactReason(value?: string | null, max = 110): string {
  if (!value) return "-";
  return value.length > max ? `${value.slice(0, max - 1)}...` : value;
}
