const labels: Record<string, string> = {
  MID_SHORT_FUTURES_LED: "Mid Short + Futures Dominan",
  MID_SHORT_NON_FUTURES_LED: "Mid Short non-Futures Dominan",
  MID_SHORT: "Mid Short",
  MID_LONG: "Mid Long",
  EARLY_LONG: "Early Long",
  EARLY_SHORT: "Early Short",
  NO_SIGNAL_CONTEXT: "Belum ada setup",
  NO_SETUP: "Belum ada setup",
  BASELINE_CONTEXT: "Baseline / pembanding",
  RISK_CONTEXT: "Konteks risiko",
  RADAR_ONLY: "Pantauan saja",
  READ_ONLY: "Read-only",
  SIGNAL_CANDIDATE: "Signal",
  WATCHLIST_CONTEXT: "Candidate",
  WATCHLIST_FOR_MORE_DATA: "Pantau dulu",
  PHASE7_READY: "Siap forward-test",
  REJECT_FOR_PHASE7: "Ditolak oleh gate",
  WAITING_FOR_APPROVED_CANDIDATE: "Menunggu kandidat approved",
  WAITING_FOR_CANDIDATE: "Menunggu kandidat",
  ACTIVE_FORWARD_TEST: "Forward-test aktif",
  ACTIVE_LAB_SHADOW: "Lab shadow aktif",
  ACTIVE_APPROVED_SHADOW: "Approved shadow aktif",
  FORWARD_TEST_COMPLETE: "Forward-test selesai",
  INPUT_ARTIFACT_MISSING: "Artifact belum lengkap",
  PHASE7_INFRA_READY_WAITING: "Infra siap, menunggu",
  PHASE7_ACTIVE_FORWARD_TEST: "Shadow test aktif",
  PHASE7_BLOCKED_BY_ERROR: "Gate blocked",
  PHASE7_DUAL_LANE_ACTIVE_LAB_SHADOW: "Lab shadow aktif",
  PHASE7_DUAL_LANE_ACTIVE_APPROVED_SHADOW: "Approved shadow aktif",
  PHASE7_DUAL_LANE_READY_WAITING: "Menunggu kandidat",
  PHASE7_DUAL_LANE_ERROR: "Forward-test error",
  APPROVED_SHADOW: "Approved Shadow",
  LAB_SHADOW: "Lab Shadow",
  STRICT_APPROVED: "Strict approved",
  LAB_NEAR_MISS: "Lab near-miss",
  WAITING_OUTCOME: "Menunggu outcome",
  TP_FIRST: "TP duluan",
  SL_FIRST: "SL duluan",
  NEITHER: "Belum kena TP/SL",
  NEITHER_CLOSE_AT_HORIZON: "Close di horizon",
  TP_HIT: "Target referensi tersentuh",
  SL_HIT: "Stop referensi tersentuh",
  SL_HIT_CONSERVATIVE: "Stop konservatif",
  BOTH_HIT_SAME_CANDLE: "Target dan stop satu candle",
  EXPIRED: "Expired",
  UNKNOWN_FORWARD_DATA: "Data forward belum cukup",
  CANNOT_EVALUATE: "Tidak bisa dievaluasi",
  CANNOT_CREATE_EVENT_MISSING_REFERENCE: "Referensi belum lengkap",
  NOISY: "Masih noise",
  MONITOR_MORE: "Pantau lagi",
  PROMISING_FOR_FORWARD_TEST: "Menarik, belum final",
  PROMISING_FILTER: "Filter menarik",
  REDUCES_DAMAGE: "Mengurangi rugi",
  NOISY_FILTER: "Filter masih noise",
  WORSE_THAN_BASELINE: "Lebih buruk dari baseline",
  REGIME_HELPFUL: "Regime membantu",
  REGIME_IMPROVES: "Regime membaik",
  REGIME_NOISY: "Regime noise",
  REGIME_BAD: "Regime buruk",
  REGIME_UNKNOWN: "Regime belum jelas",
  RISK_ON: "Risk on",
  RISK_OFF: "Risk off",
  BTC_UP_BREADTH_WEAK: "BTC naik, market lemah",
  BTC_DOWN_BREADTH_STRONG: "BTC turun, market kuat",
  CHOPPY_OR_MIXED: "Choppy / mixed",
  BULLISH: "Bullish",
  BEARISH: "Bearish",
  FLAT: "Flat",
  UNKNOWN: "Unknown",
  BREADTH_STRONG: "Market breadth kuat",
  BREADTH_WEAK: "Market breadth lemah",
  BREADTH_MIXED: "Market breadth mixed",
  BREADTH_UNKNOWN: "Breadth belum jelas",
  VOL_HIGH: "Volatilitas tinggi",
  VOL_NORMAL: "Volatilitas normal",
  VOL_LOW: "Volatilitas rendah",
  VOL_UNKNOWN: "Volatilitas belum jelas",
  PROMISING: "Menarik, belum final",
  V3_FORWARD_HEALTHY_SHADOW: "V3 sehat",
  V3_FORWARD_MONITOR_MORE: "V3 pantau lanjut",
  V3_FORWARD_WAITING_SAMPLE: "V3 tunggu sample",
  V3_FORWARD_WEAK: "V3 lemah",
  V3_FORWARD_INCONCLUSIVE: "V3 belum jelas",
  V3_SHADOW_IMPROVES_V2: "V3 membaik vs V2",
  V3_SHADOW_MONITOR_MORE: "V3 pantau lanjut",
  V3_SHADOW_WEAKER_THAN_V2: "V3 lebih lemah",
  V3_SHADOW_INCONCLUSIVE: "V3 belum jelas",
  V3_SAMPLE_TOO_SMALL: "Sample V3 kecil",
  QUALITY_POSITIVE: "Kualitas positif",
  TOTAL_R_POSITIVE_MEDIAN_WEAK: "Total positif, median lemah",
  QUALITY_WEAK: "Kualitas lemah",
  NOISY_MIXED: "Campuran/noise",
  SAMPLE_TOO_SMALL: "Sample kecil",
  INSUFFICIENT_SAMPLE: "Sample kurang",
  REJECT: "Ditolak",
  PARTIAL_DATA: "Data sebagian",
  MISSING_ATR: "ATR belum tersedia",
  MISSING_CANDLES: "Candle belum cukup",
  TIMEFRAME_NOT_READY: "Timeframe belum siap",
  TIMEFRAME_PARTIAL_USABLE: "Bisa dipakai sebagian",
  TIMEFRAME_READY: "Timeframe siap",
  BLOCKED_DATA: "Data belum cukup",
  CONFLICTED: "Konteks campuran",
  BULLISH_CONTEXT: "Condong naik",
  BEARISH_CONTEXT: "Condong turun",
  MIXED_CONTEXT: "Campuran",
  MIXED: "Campuran",
  HIGH: "Tinggi",
  MEDIUM: "Sedang",
  LOW: "Rendah",
  HAS_CANDIDATES: "Ada kandidat lolos gate",
  NO_PHASE7_CANDIDATE_YET: "Belum ada kandidat lolos gate",
  READY: "Siap",
  WARMUP: "Pemanasan data",
  STALE: "Data tertinggal",
  MISSING_SPOT: "Spot belum tersedia",
  MISSING_FUTURES: "Futures belum tersedia",
  MISSING_OI: "OI belum tersedia",
  MISSING_FUNDING: "Funding belum tersedia",
  AGG_READY: "Siap",
  AGG_INCOMPLETE: "Belum lengkap",
  AGG_WARMUP: "Pemanasan data",
  AGG_STALE: "Data tertinggal",
  AGG_MISSING_SPOT: "Spot belum tersedia",
  ALIGNED: "Aligned",
  INCOMPLETE: "Belum lengkap",
  NO_DATA: "Belum ada data",
  FRESH: "Fresh",
  FUNDING_ALIGNED: "Funding aligned",
  FUNDING_CARRIED_FORWARD: "Funding carry-forward",
  FUNDING_STALE: "Funding stale",
  FUNDING_MISSING: "Funding missing",
  FEATURE_READY: "Feature siap",
  FEATURE_PARTIAL: "Feature sebagian",
  FEATURE_BLOCKED: "Feature blocked",
  CONTEXT_READY: "Context siap",
  CONTEXT_PARTIAL: "Context sebagian",
  CONTEXT_BLOCKED: "Context blocked",
  OUTCOME_READY: "Outcome siap",
  OUTCOME_WAITING_DATA: "Menunggu data",
  OUTCOME_INCOMPLETE: "Outcome belum lengkap",
  OUTCOME_BLOCKED: "Outcome blocked",
  STALE_FORWARD_DATA: "Data forward stale",
  STALE_FOUND: "Ada data stale",
  WAITING_DATA: "Menunggu data",
  ACTIVE: "Aktif",
  NOT_ACTIVE: "Tidak aktif",
  FULL_ACTIVE: "Full active",
  LIGHT_WATCH: "Light watch",
  PASS: "Pass",
  FAIL: "Fail",
  FILL_GOOD: "Fill realistis bagus",
  FILL_ACCEPTABLE: "Fill realistis cukup",
  FILL_BAD: "Fill realistis buruk",
  FILL_UNKNOWN: "Fill belum jelas",
  SECOND_FILTER_MONITOR: "Second filter pantau",
  SECOND_FILTER_REDUCES_DAMAGE: "Mengurangi damage",
  SECOND_FILTER_NO_CLEAR_EDGE: "Belum ada edge jelas",
  SECOND_FILTER_WORSE: "Lebih buruk",
  WAIT_MORE_SAMPLE: "Tunggu sample",
  TAKER_DEEP_FILTER_PROMISING: "Taker filter menarik",
  TAKER_DEEP_FILTER_REDUCES_DAMAGE: "Taker filter kurangi damage",
  TAKER_DEEP_NO_CLEAR_EDGE: "Belum ada edge jelas",
  TAKER_DEEP_FILTER_WORSE: "Lebih buruk",
  TAKER_DEEP_WAIT_MORE_SAMPLE: "Tunggu sample",
  WRONG_DIR_FILTER_PROMISING: "Anti salah-arah menarik",
  WRONG_DIR_FILTER_REDUCES_DAMAGE: "Mengurangi salah arah",
  WRONG_DIR_NO_CLEAR_EDGE: "Belum ada gap jelas",
  WRONG_DIR_FILTER_WORSE: "Lebih buruk",
  WRONG_DIR_WAIT_MORE_SAMPLE: "Tunggu sample",
  HAS_WRONG_DIR_PROMISING_FILTER: "Ada filter salah-arah menarik",
  HAS_WRONG_DIR_DAMAGE_REDUCTION: "Ada filter kurangi salah-arah",
  NO_WRONG_DIRECTION_CLEAN_FILTER_YET: "Belum ada filter bersih",
  NO_WRONG_DIRECTION_FILTER_ROWS: "Belum ada baris filter",
  VOLUME_SAFE_SHADOW_MONITOR: "Volume-safe pantau shadow",
  VOLUME_SAFE_REDUCES_DAMAGE: "Volume-safe kurangi damage",
  VOLUME_SAFE_NO_CLEAR_EDGE: "Volume-safe belum jelas",
  VOLUME_SAFE_WAIT_MORE_SAMPLE: "Volume-safe tunggu sample",
  VOLUME_SAFE_PASS: "Volume aman",
  VOLUME_SAFE_FAIL: "Volume meledak",
  VOLUME_SAFE_MISSING: "Volume missing",
  COMBO_SHADOW_CANDIDATE: "Kandidat V2.1 shadow",
  COMBO_REDUCES_DAMAGE: "Kombinasi kurangi damage",
  COMBO_NO_CLEAR_EDGE: "Kombinasi belum jelas",
  COMBO_WAIT_MORE_SAMPLE: "Kombinasi tunggu sample",
  COMBO_REJECT: "Kombinasi ditolak",
  HAS_V2_1_SHADOW_CANDIDATE: "Ada kandidat V2.1 shadow",
  HAS_COMBO_DAMAGE_REDUCTION: "Ada kombinasi kurangi damage",
  NO_CLEAN_COMBO_FILTER_YET: "Belum ada kombinasi bersih",
  NO_COMBO_FILTER_ROWS: "Belum ada kombinasi",
  REVERSE_HYPOTHESIS_WORTH_TESTING: "Reverse layak diteliti",
  DIRECTION_IDENTIFICATION_WEAK: "Identifikasi arah lemah",
  RISK_OR_ENTRY_MODEL_WEAK: "Entry/risk model lemah",
  DIRECTION_ACCEPTABLE_MONITOR: "Arah cukup, pantau",
  NO_CLEAR_FIX_YET: "Belum ada fix jelas",
  REVERSE_WORTH_RESEARCH: "Reverse perlu riset",
  DIRECTION_WEAK: "Arah lemah",
  ENTRY_FILTER_CANDIDATE: "Kandidat filter entry",
  STOP_OR_TIMEOUT_RESEARCH: "Riset stop/timeout",
  HEALTHY_BUCKET: "Bucket sehat",
  LOSS_BUCKET: "Bucket loss",
  WRONG_DIRECTION_REVERSE_CANDIDATE: "Salah arah, reverse candidate",
  WRONG_DIRECTION_PERSISTENT: "Salah arah berlanjut",
  WRONG_DIRECTION_SHORT_TERM: "Salah arah jangka pendek",
  CHOPPY_BOTH_SIDE_RISK: "Choppy dua arah",
  STOP_OR_TIMING_PROBLEM: "Masalah stop/timing",
  FAVORABLE_THEN_REVERSED: "Sempat benar lalu balik",
  ENTRY_OVEREXTENDED: "Entry terlalu telat",
  COST_OR_FILL_DRAG: "Cost/fill drag",
  MIXED_OR_NO_CLEAR_CAUSE: "Penyebab campuran",
  STOP_TOO_TIGHT: "Stop terlalu dekat",
  TARGET_TOO_FAR: "Target terlalu jauh",
  REGIME_CONFLICT: "Konflik regime",
  LATE_ENTRY: "Entry terlambat",
  NO_FOLLOWTHROUGH: "Tidak ada follow-through",
  MIXED_UNRESOLVED: "Penyebab belum terurai",
  SL_PRIMARY_STOP_TOO_TIGHT: "Penyebab utama: stop terlalu dekat",
  SL_PRIMARY_TARGET_TOO_FAR: "Penyebab utama: target terlalu jauh",
  SL_PRIMARY_REGIME_CONFLICT: "Penyebab utama: konflik regime",
  SL_PRIMARY_LATE_ENTRY: "Penyebab utama: entry terlambat",
  SL_PRIMARY_WRONG_DIRECTION: "Penyebab utama: salah arah",
  SL_PRIMARY_NO_FOLLOWTHROUGH: "Penyebab utama: tidak ada follow-through",
  SL_PRIMARY_MIXED_UNRESOLVED: "Penyebab utama belum terurai",
  PATH_CONFIRMED: "Dibuktikan jalur harga",
  PATH_SUPPORTED: "Didukung jalur harga",
  CONTEXT_SUPPORTED: "Didukung konteks market",
  EVIDENCE_SUPPORTED: "Didukung evidence signal",
  UNRESOLVED: "Belum terurai",
  NOT_APPLICABLE: "Tidak berlaku",
  REVERSE_CLEAN_PROXY: "Reverse clean proxy",
  REVERSE_BOTH_ZONE_PROXY: "Reverse kena dua sisi",
  REVERSE_WOULD_SL_PROXY: "Reverse juga SL",
  REVERSE_NO_TP_PROXY: "Reverse tidak TP",
  REVERSE_UNKNOWN: "Reverse unknown",
  ENTRY_EXTENSION_OK: "Entry extension OK",
  RANGE_OVEREXTENDED: "Range overextended",
  PRICE_ATR_OVEREXTENDED: "Price/ATR overextended",
  ATR_EXTENSION_OVEREXTENDED: "ATR extension tinggi",
  LONG_AFTER_STRONG_GREEN: "Long setelah candle kuat",
  SHORT_AFTER_STRONG_RED: "Short setelah candle merah kuat",
  COST_FILL_OK: "Cost/fill OK",
  IDEAL_WIN_REALISTIC_LOSS: "Ideal menang, realistis kalah",
  HIGH_REALISM_PENALTY: "Penalty realistis tinggi",
  IMMEDIATE_REVERSAL: "Langsung reversal",
  BTC_ETH_PULL_UP: "Tertarik BTC/ETH naik",
  SELL_ABSORPTION: "Sell diserap buyer",
  STOP_RUN_THEN_DROP: "Stop dulu lalu turun",
  NO_SELL_FOLLOWTHROUGH: "Sell tidak followthrough",
  GRIND_UP: "Naik perlahan",
  WRONG_DIRECTION_OTHER: "Salah arah lain",
  CORRECT_DIRECTION: "Arah benar",
  WRONG_DIRECTION: "Salah arah",
  FLAT_1H: "Flat 1h",
  UP_STRONG: "Naik kuat",
  UP: "Naik",
  DOWN_STRONG: "Turun kuat",
  DOWN: "Turun",
  SHORT_FOLLOWTHROUGH_1H: "Short followthrough 1h",
  EARLY_DROP_THEN_REBOUND: "Turun awal lalu rebound",
  NO_FOLLOWTHROUGH_IMMEDIATE_REVERSAL: "Tidak followthrough, reversal cepat",
  NO_SHORT_FOLLOWTHROUGH_1H: "Tidak followthrough 1h",
  FOLLOWTHROUGH_UNKNOWN: "Followthrough belum jelas",
  CORRECT_HIGHER: "Lebih tinggi di arah benar",
  WRONG_HIGHER: "Lebih tinggi di salah arah",
  NO_CLEAR_GAP: "Gap tidak jelas",
  ATR_INFLATED: "ATR membesar",
  LATE_ENTRY_EXTENSION: "Entry sudah terentang",
  VOLATILITY_CONTRACTION: "Volatilitas menyusut",
  STRUCTURE_BLOCK: "Terhalang support",
  STRUCTURE_CLEAR: "Structure clear",
  STRUCTURE_BLOCKED: "Structure blocked",
  STRUCTURE_UNAVAILABLE: "Structure belum tersedia",
  ZONE_ALIGNED: "Zona selaras",
  ZONE_CONFLICT: "Konflik zona",
  ZONE_NEUTRAL: "Zona netral",
  ZONE_UNAVAILABLE: "Zona belum tersedia",
  ZONE_PENDING: "Menunggu snapshot zona",
  ZONE_NOT_APPLICABLE: "Zona tidak berlaku",
  COMPARABLE: "Sample dapat dibandingkan",
  AT_SUPPORT: "Di support",
  AT_RESISTANCE: "Di resistance",
  SUPPORT_BOUNCE: "Pantulan support",
  RESISTANCE_REJECTION: "Penolakan resistance",
  SUPPORT_BREAK: "Support pecah",
  RESISTANCE_BREAKOUT: "Resistance ditembus",
  BREAK_RETEST_REJECTED: "Retest support ditolak",
  BREAKOUT_RETEST_HELD: "Retest resistance bertahan",
  FAILED_BREAKDOWN_RECLAIM: "Breakdown gagal lalu reclaim",
  FAILED_BREAKOUT_REJECT: "Breakout gagal lalu ditolak",
  PINCHED_BETWEEN_ZONES: "Terjepit dua zona",
  MIXED_STRUCTURE_INTERACTION: "Interaksi zona campuran",
  MID_RANGE: "Tengah range",
  AT_1H_SUPPORT: "Di support 1h",
  AT_1H_RESISTANCE: "Di resistance 1h",
  "1H_RESISTANCE_REJECTED": "Resistance 1h ditolak",
  "1H_SUPPORT_BREAK": "Support 1h pecah",
  "1H_BREAK_RETEST_REJECTED": "Retest break 1h ditolak",
  "1H_FAILED_BREAK_RECLAIM": "Break gagal, reclaim 1h",
  "1H_MID_RANGE": "Tengah range 1h",
  "1H_ZONE_UNAVAILABLE": "Zona 1h belum tersedia",
  ALIGNED_WITH_4H_RESISTANCE: "Selaras resistance 4h",
  CONFLICT_WITH_4H_SUPPORT: "Konflik support 4h",
  NO_4H_CONFLUENCE: "Tanpa confluence 4h",
  FOUR_H_CONTEXT_UNAVAILABLE: "Context 4h belum tersedia",
  STRUCTURE_VALIDATION_IMPROVES: "Membaik di validation",
  STRUCTURE_REDUCES_DAMAGE_ONLY: "Hanya kurangi damage",
  STRUCTURE_TRAIN_ONLY: "Hanya bagus di train",
  STRUCTURE_NO_CLEAR_GAIN: "Belum ada gain jelas",
  STRUCTURE_NEEDS_MORE_SAMPLE: "Butuh sample tambahan",
  TRAIN_SELECTED: "Dipilih dari train",
  AVOID_1H_SUPPORT_CONFLICT: "Hindari konflik support 1h",
  SHORT_STRUCTURE_CONFIRMED: "Struktur short terkonfirmasi",
  RESISTANCE_OR_BREAK_CONTEXT: "Resistance atau break context",
  CONFIRMED_SWING_LOW_1H: "Confirmed swing low 1h",
  PERIOD_LOW_FALLBACK_1H: "Fallback low 24 candle 1h",
  MOMENTUM_DECAY: "Momentum melemah",
  RR_GEOMETRY_MISMATCH: "Geometri RR tidak cocok",
  CONTEXT_COMPLETE: "Context lengkap",
  CONTEXT_MISSING: "Context hilang",
  TARGET_DISTANCE_NEEDS_MORE_SAMPLE: "Target study perlu sample",
  TARGET_DISTANCE_HAS_TESTABLE_HYPOTHESIS: "Ada hipotesis yang bisa diuji",
  EXIT_GEOMETRY_IMPROVES_FIXED_COHORT_MONITOR: "Exit geometry membaik, pantau",
  TARGET_DISTANCE_NO_CLEAN_FIX_YET: "Belum ada fix target yang bersih",
  STRUCTURE_CLEARANCE_NEEDS_MORE_SAMPLE: "Structure perlu sample lagi",
  STRUCTURE_CLEARANCE_VALIDATION_IMPROVES: "Structure clear membaik di validation",
  STRUCTURE_CLEARANCE_REDUCES_DAMAGE_MONITOR: "Structure clear mengurangi damage",
  STRUCTURE_CLEARANCE_NO_CLEAR_EDGE: "Structure belum memberi pemisahan",
  CURRENT_CONTROL: "Control saat ini",
  VALIDATION_IMPROVES_FIXED_COHORT: "Validation fixed-cohort membaik",
  TRAIN_ONLY_IMPROVEMENT: "Hanya train membaik",
  NO_CLEAR_IMPROVEMENT: "Belum ada perbaikan jelas",
  NEEDS_MORE_SAMPLE: "Perlu sample lagi",
  CONTROL_LOGGED: "Target logged",
  TP_0_75R: "Target fixed 0.75R",
  SUPPORT_TOUCH: "Sentuh support",
  SUPPORT_COST_BUFFER: "Support + cost buffer",
  LOGGED_TARGET: "Target tercatat",
  FIXED_R_REFERENCE: "Referensi R tetap",
  SUPPORT_REFERENCE: "Referensi support 1h",
  SUPPORT_EXECUTION_BUFFER: "Support dengan buffer biaya",
  FIXED_TARGET_REFERENCE: "Referensi target tetap",
  SUPPORT_TARGET_VALIDATION_IMPROVES: "Target support membaik di validation",
  SUPPORT_TARGET_REDUCES_DAMAGE_ONLY: "Target support hanya mengurangi damage",
  SUPPORT_TARGET_TRAIN_ONLY: "Target support hanya membaik di train",
  SUPPORT_TARGET_NO_IMPROVEMENT: "Target support belum membaik",
  SUPPORT_TARGET_NEEDS_MORE_SAMPLE: "Target support perlu sample lagi",
  CONTROL_IMMEDIATE: "Entry langsung (control)",
  WAIT_15M_ALWAYS: "Tunggu satu candle 15m",
  VETO_UP_REVERSAL_0_05: "Veto reversal naik >= 0.05%",
  CONFIRM_CLOSE_BELOW_ENTRY: "Konfirmasi close di bawah entry",
  CONFIRM_BELOW_ENTRY_TAKER_SELL_52: "Konfirmasi turun + taker sell >= 52%",
  FILTERED_NO_ENTRY: "Tidak masuk setelah konfirmasi",
  MISSING_CONFIRMATION: "Candle konfirmasi belum tersedia",
  CONFIRMATION_VALIDATION_IMPROVES: "Konfirmasi membaik di validation",
  CONFIRMATION_REDUCES_DAMAGE_ONLY: "Konfirmasi hanya mengurangi damage",
  CONFIRMATION_TRAIN_ONLY: "Konfirmasi hanya membaik di train",
  CONFIRMATION_NEEDS_MORE_SAMPLE: "Konfirmasi perlu sample lagi",
  CONFIRMATION_NO_IMPROVEMENT: "Konfirmasi belum membaik",
  CONFIRMATION_NO_CLEAR_GAIN: "Belum ada gain konfirmasi yang bersih",
  UPWARD_CONFIRMATION_LOSS_HEAVY: "Konfirmasi naik dominan loss",
  SHORT_CONFIRMATION_HEALTHIER: "Konfirmasi short lebih sehat",
  MIXED_PATH: "Jalur bercampur",
  WAITING_4H: "Menunggu jalur 4h lengkap",
  INVALID_TARGET_GEOMETRY: "Geometri target tidak valid",
  SPREAD_UNKNOWN: "Spread belum diketahui",
  INFO: "Info",
  UNAVAILABLE: "Belum tersedia"
};

export function labelFor(value?: string | null): string {
  if (!value) return "-";
  return labels[value] || value.replaceAll("_", " ").toLowerCase().replace(/^\w/, (char) => char.toUpperCase());
}

export function compactReason(value?: string | null, max = 110): string {
  if (!value) return "-";
  return value.length > max ? `${value.slice(0, max - 1)}...` : value;
}
